/**
 * S16 RUN_RESOLUTION and S17 DEBRIEF.
 *
 * Evaluate every attack, hazard, team loss and objective fact belonging to the
 * completed step, then commit exactly one result [§4.4:1224]. Precedence is
 * irrecoverable failure, then mandatory survival, then victory [§6.6:1537 step 7].
 */
import { hull } from "./content.ts";
import { log } from "./log.ts";
import { allTeamsLost } from "./rules/r5-recovery.ts";
import { travelCost } from "./campaign.ts";
import { currentSector, type RunState } from "./state.ts";
import { STOCK_KEYS, type TerminalOutcome } from "./types.ts";

export interface Terminal {
  outcome: TerminalOutcome;
  reason: string;
}

/**
 * Runs after each completed atomic campaign action, never mid-step [§1.4:124].
 * Zero ammunition or fuel alone never kills the ship [§4.4:1234]; being unable
 * to move with nothing left to try does.
 */
export function terminalCheck(s: RunState): Terminal | null {
  if (s.conditions.hull <= 0) {
    return { outcome: "defeat", reason: "hull reached zero" };
  }
  // Two independent sinking countdowns [§1.9:269, §6.3:1401]. Step 1 has no
  // tactical clock to run them on, so it commits the condition directly.
  if (s.conditions.stability < 10) {
    return { outcome: "defeat", reason: "stability gone: she went over" };
  }
  if (allTeamsLost(s)) {
    return { outcome: "defeat", reason: "every team lost" };
  }
  if (strandedWithNoRecovery(s)) {
    return {
      outcome: "stranded",
      reason: "out of fuel with no reachable source and nothing left to sell",
    };
  }
  return null;
}

/**
 * Fuel exhaustion with no tow or aid [§4.4:1226]. A clear run-ending decision
 * exists rather than an endless empty map [§6.9:1655], so this only fires when
 * the cheapest next leg is unaffordable and no port sale can cover it.
 */
function strandedWithNoRecovery(s: RunState): boolean {
  if (s.stocks.fuel > 1) return false;
  const sector = currentSector(s);
  const next = sector.layers[s.layerIndex + 1];
  if (!next || next.length === 0) return false;
  const cheapest = Math.min(...next.map((n) => travelCost(s, n).fuel));
  if (cheapest <= s.stocks.fuel) return false;
  // Selling surplus is a recovery path [R10.6], and it is only gone when there
  // is nothing left worth anything.
  const sellable = STOCK_KEYS.some((k) => k !== "fuel" && s.stocks[k] > 5);
  return !sellable && s.scrap < 5;
}

export function commitTerminal(s: RunState, t: Terminal): void {
  if (s.lifecycle !== "ACTIVE") return;
  // ACTIVE -> TERMINAL_PENDING -> ARCHIVED, monotonic [§3.5:1150]. The pending
  // state exists so a crash between "the run ended" and "the profile recorded
  // it" resolves once, granting nothing twice [§3.5:1155].
  s.lifecycle = "TERMINAL_PENDING";
  s.outcome = t.outcome;
  s.outcomeReason = t.reason;
  s.state = "DEBRIEF";
  log(s, "terminal", `${t.outcome}: ${t.reason}`, { outcome: t.outcome });
}

export interface Debrief {
  outcome: TerminalOutcome;
  reason: string;
  seed: number;
  faction: string;
  build: string;
  sectorsReached: number;
  nodesVisited: number;
  hours: number;
  bossArchetype: string;
  bossPhaseReached: number;
  bossDestroyed: boolean;
  teamsLost: string[];
  suppliesSpent: Record<string, number>;
  scrap: number;
  upgrades: number;
  modules: string[];
  timeline: string[];
}

export function debrief(s: RunState): Debrief {
  const h = hull(s.hullId);
  return {
    outcome: s.outcome ?? "abandoned",
    reason: s.outcomeReason,
    seed: s.seed,
    faction: s.faction,
    build: `${h.name} / ${s.deck} / ${s.supportId}`,
    sectorsReached: s.sectorIndex + 1,
    nodesVisited: s.nodesVisited,
    hours: Math.round(s.hours),
    bossArchetype: s.boss.name,
    bossPhaseReached: s.pendingFight?.boss
      ? phaseOf(s.pendingFight.enemyHp / s.pendingFight.enemyHpMax)
      : (s.flags.has("boss_engaged") ? 2 : 0),
    bossDestroyed: s.flags.has("boss_destroyed"),
    teamsLost: s.teams.filter((t) => t.lost).map((t) => t.name),
    suppliesSpent: spentByKind(s),
    scrap: Math.round(s.scrap),
    upgrades: s.upgrades,
    modules: s.modules,
    timeline: timeline(s),
  };
}

function phaseOf(share: number): number {
  if (share > 0.70) return 0;
  if (share > 0.35) return 1;
  return 2;
}

function spentByKind(s: RunState): Record<string, number> {
  const out: Record<string, number> = {};
  for (const e of s.log) {
    for (const [k, v] of Object.entries(e.facts ?? {})) {
      if (typeof v === "number" && (STOCK_KEYS as string[]).includes(k) && v < 0) {
        out[k] = (out[k] ?? 0) + -v;
      }
    }
  }
  return out;
}

/**
 * R10.4 · The cause-and-effect chain is generated by walking the log, not by
 * reading authored strings. The design document's own example of a good
 * timeline is at §4.6:1250: heavy volley, generator lost, pump output fell,
 * teams left the guns to patch flooding, ammunition remained but offensive
 * uptime collapsed.
 */
function timeline(s: RunState): string[] {
  const notable = s.log.filter((e) => {
    if (e.kind === "terminal" || e.kind === "crew") return true;
    if (e.kind === "fight") return (e.facts?.hullLost as number ?? 0) >= 8;
    if (e.kind === "hazard") return true;
    if (e.kind === "rations") return true;
    if (e.kind === "sector") return true;
    if (e.kind === "arrival") return true;
    return false;
  });
  // Keep the chain readable: the first, the last, and the heaviest in between.
  const head = notable.slice(0, 3);
  const tail = notable.slice(-4);
  const middle = notable
    .slice(3, -4)
    .sort((a, b) => (b.facts?.hullLost as number ?? 0) - (a.facts?.hullLost as number ?? 0))
    .slice(0, 3)
    .sort((a, b) => a.hours - b.hours);
  const seen = new Set<string>();
  return [...head, ...middle, ...tail]
    .filter((e) => {
      const key = `${e.hours}:${e.text}`;
      if (seen.has(key)) return false;
      seen.add(key);
      return true;
    })
    .map((e) => `h${String(Math.round(e.hours)).padStart(3)} S${e.sector} ${e.text}`);
}
